id: IFFECB1E9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T10:00:06+00:00'
last_modified: '2022-06-10T05:05:55.379154+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17467
  title: ཏཱ་རེ་ལྷ་མོ་དང་ནམ་སྤྲུལ་འཇིགས་མེད་ཕུན་ཚོགས་ཀྱི་གཏེར་ཆོས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F976:
      image_group_id: I4PD2916
      title: Volume 1 of tA re lha mo dang nam sprul 'jigs med phun tshogs kyi gter
        chos/
      total_pages: 298
      order: 1
      base_file: F976.txt
    0FFB:
      image_group_id: I4PD2917
      title: Volume 2 of tA re lha mo dang nam sprul 'jigs med phun tshogs kyi gter
        chos/
      total_pages: 194
      order: 2
      base_file: 0FFB.txt
    '7744':
      image_group_id: I4PD2918
      title: Volume 3 of tA re lha mo dang nam sprul 'jigs med phun tshogs kyi gter
        chos/
      total_pages: 159
      order: 3
      base_file: 7744.txt
    '5137':
      image_group_id: I4PD2919
      title: Volume 4 of tA re lha mo dang nam sprul 'jigs med phun tshogs kyi gter
        chos/
      total_pages: 207
      order: 4
      base_file: 5137.txt
    D733:
      image_group_id: I4PD2920
      title: Volume 5 of tA re lha mo dang nam sprul 'jigs med phun tshogs kyi gter
        chos/
      total_pages: 210
      order: 5
      base_file: D733.txt
    28A2:
      image_group_id: I4PD2921
      title: Volume 6 of tA re lha mo dang nam sprul 'jigs med phun tshogs kyi gter
        chos/
      total_pages: 295
      order: 6
      base_file: 28A2.txt
    800F:
      image_group_id: I4PD2922
      title: Volume 7 of tA re lha mo dang nam sprul 'jigs med phun tshogs kyi gter
        chos/
      total_pages: 192
      order: 7
      base_file: 800F.txt
    2D91:
      image_group_id: I4PD2923
      title: Volume 8 of tA re lha mo dang nam sprul 'jigs med phun tshogs kyi gter
        chos/
      total_pages: 226
      order: 8
      base_file: 2D91.txt
    479C:
      image_group_id: I4PD2924
      title: Volume 9 of tA re lha mo dang nam sprul 'jigs med phun tshogs kyi gter
        chos/
      total_pages: 220
      order: 9
      base_file: 479C.txt
    F066:
      image_group_id: I4PD2925
      title: Volume 10 of tA re lha mo dang nam sprul 'jigs med phun tshogs kyi gter
        chos/
      total_pages: 192
      order: 10
      base_file: F066.txt
    5D5B:
      image_group_id: I4PD2926
      title: Volume 11 of tA re lha mo dang nam sprul 'jigs med phun tshogs kyi gter
        chos/
      total_pages: 148
      order: 11
      base_file: 5D5B.txt
    748A:
      image_group_id: I4PD2927
      title: Volume 12 of tA re lha mo dang nam sprul 'jigs med phun tshogs kyi gter
        chos/
      total_pages: 148
      order: 12
      base_file: 748A.txt
    5A60:
      image_group_id: I4PD2928
      title: Volume 13 of tA re lha mo dang nam sprul 'jigs med phun tshogs kyi gter
        chos/
      total_pages: 556
      order: 13
      base_file: 5A60.txt
    '5464':
      image_group_id: I4PD2929
      title: Volume 14 of tA re lha mo dang nam sprul 'jigs med phun tshogs kyi gter
        chos/
      total_pages: 344
      order: 14
      base_file: 5464.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
